'use client';

import { useEffect, useState } from 'react';
import {
  ABILITY_TIERS,
  ABILITY_TIER_LABELS,
  DISCIPLINES,
  DISCIPLINE_LABELS,
  effectiveProfile,
  type AbilityTier,
  type ClimbDiscipline,
  type ProfilePatch,
  type ProfileSettings,
} from '@tfc/core';
import { Card } from '../../../components/Card';
import { OptionChips, type ChipOption } from '../../../components/OptionChips';
import { PageHeader } from '../../../components/PageHeader';
import { Screen } from '../../../components/Screen';
import { useRepository } from '../../../lib/db/RepositoryProvider';

const TIER_OPTIONS: ChipOption<AbilityTier>[] = ABILITY_TIERS.map((t) => ({
  label: ABILITY_TIER_LABELS[t.id],
  value: t.id,
}));
const DISCIPLINE_OPTIONS: ChipOption<ClimbDiscipline>[] = DISCIPLINES.map((d) => ({
  label: DISCIPLINE_LABELS[d],
  value: d,
}));
const REASSESS_OPTIONS: ChipOption<string>[] = ['4', '6', '8', '12'].map((w) => ({
  label: `${w} wks`,
  value: w,
}));
const AI_OPTIONS: ChipOption<'on' | 'off'>[] = [
  { label: 'On', value: 'on' },
  { label: 'Off', value: 'off' },
];

export default function ProfilePage() {
  const repo = useRepository();
  const [settings, setSettings] = useState<ProfileSettings | null>(null);

  useEffect(() => {
    repo.getProfile().then((p) => setSettings(effectiveProfile(p)));
  }, [repo]);

  const update = async (patch: ProfilePatch) => {
    const saved = await repo.saveProfile(patch);
    setSettings(effectiveProfile(saved));
  };

  return (
    <>
      <PageHeader title="Profile" />
      {settings === null ? (
        <Screen />
      ) : (
        <Screen>
          <p className="text-sm leading-6 text-muted">
            These settings tailor your daily suggestion, defaults, and reminders.
          </p>

          <Card>
            <p className="mb-2 font-semibold">Ability tier</p>
            <OptionChips
              options={TIER_OPTIONS}
              selected={settings.abilityTier}
              onSelect={(v) => update({ abilityTier: v })}
            />
          </Card>

          <Card>
            <p className="mb-2 font-semibold">Default discipline</p>
            <OptionChips
              options={DISCIPLINE_OPTIONS}
              selected={settings.defaultDiscipline}
              onSelect={(v) => update({ defaultDiscipline: v })}
            />
          </Card>

          <Card>
            <p className="mb-2 font-semibold">Re-assess every</p>
            <p className="mb-2 text-sm leading-5 text-muted">
              How often to nudge you to retake the self-assessment.
            </p>
            <OptionChips
              options={REASSESS_OPTIONS}
              selected={String(settings.reassessWeeks)}
              onSelect={(v) => update({ reassessWeeks: Number(v) })}
            />
          </Card>

          <Card>
            <p className="mb-2 font-semibold">AI coach</p>
            <p className="mb-2 text-sm leading-5 text-muted">
              When on, your daily suggestion is generated by an AI from your assessments, recent
              journals, and climbs (requires a configured sync server). Off uses the built-in
              rule-based suggestion. Your data is sent to your own server, which calls the AI
              provider.
            </p>
            <OptionChips
              options={AI_OPTIONS}
              selected={settings.aiCoachEnabled ? 'on' : 'off'}
              onSelect={(v) => update({ aiCoachEnabled: v === 'on' })}
            />
          </Card>
        </Screen>
      )}
    </>
  );
}
