import {
  ABILITY_TIER_LABELS,
  ABILITY_TIERS,
  type AbilityTier,
  type ClimbDiscipline,
  DISCIPLINE_LABELS,
  DISCIPLINES,
  effectiveProfile,
  type ProfilePatch,
  type ProfileSettings,
} from '@tfc/core';
import React, { useEffect, useState } from 'react';
import { StyleSheet, Text } from 'react-native';

import { Card } from '../../components/Card';
import { OptionChips, type ChipOption } from '../../components/OptionChips';
import { Screen } from '../../components/Screen';
import { useRepository } from '../../providers/RepositoryProvider';
import { colors, fontSize, spacing } from '../../theme';

const TIER_OPTIONS: ChipOption<AbilityTier>[] = ABILITY_TIERS.map((t) => ({
  label: ABILITY_TIER_LABELS[t.id],
  value: t.id,
}));
const DISCIPLINE_OPTIONS: ChipOption<ClimbDiscipline>[] = DISCIPLINES.map((d) => ({
  label: DISCIPLINE_LABELS[d],
  value: d,
}));
const REASSESS_OPTIONS: ChipOption<string>[] = ['4', '6', '8', '12'].map((w) => ({
  label: `${w} wks`,
  value: w,
}));
const AI_OPTIONS: ChipOption<'on' | 'off'>[] = [
  { label: 'On', value: 'on' },
  { label: 'Off', value: 'off' },
];

export function ProfileScreen() {
  const repo = useRepository();
  const [settings, setSettings] = useState<ProfileSettings | null>(null);

  useEffect(() => {
    repo.getProfile().then((p) => setSettings(effectiveProfile(p)));
  }, [repo]);

  if (!settings) return <Screen />;

  const update = async (patch: ProfilePatch) => {
    const saved = await repo.saveProfile(patch);
    setSettings(effectiveProfile(saved));
  };

  return (
    <Screen>
      <Text style={styles.title}>Profile</Text>
      <Text style={styles.subtitle}>
        These settings tailor your daily suggestion, defaults, and reminders.
      </Text>

      <Card style={styles.card}>
        <Text style={styles.label}>Ability tier</Text>
        <OptionChips
          options={TIER_OPTIONS}
          selected={settings.abilityTier}
          onSelect={(v) => update({ abilityTier: v })}
          testIDPrefix="tier"
        />
      </Card>

      <Card style={styles.card}>
        <Text style={styles.label}>Default discipline</Text>
        <OptionChips
          options={DISCIPLINE_OPTIONS}
          selected={settings.defaultDiscipline}
          onSelect={(v) => update({ defaultDiscipline: v })}
          testIDPrefix="discipline"
        />
      </Card>

      <Card style={styles.card}>
        <Text style={styles.label}>Re-assess every</Text>
        <Text style={styles.hint}>How often to nudge you to retake the self-assessment.</Text>
        <OptionChips
          options={REASSESS_OPTIONS}
          selected={String(settings.reassessWeeks)}
          onSelect={(v) => update({ reassessWeeks: Number(v) })}
          testIDPrefix="reassess"
        />
      </Card>

      <Card style={styles.card}>
        <Text style={styles.label}>AI coach</Text>
        <Text style={styles.hint}>
          When on, your daily suggestion is generated by an AI from your assessments, recent
          journals, and climbs (requires a configured sync server). Off uses the built-in rule-based
          suggestion. Your data is sent to your own server, which calls the AI provider.
        </Text>
        <OptionChips
          options={AI_OPTIONS}
          selected={settings.aiCoachEnabled ? 'on' : 'off'}
          onSelect={(v) => update({ aiCoachEnabled: v === 'on' })}
          testIDPrefix="ai"
        />
      </Card>
    </Screen>
  );
}

const styles = StyleSheet.create({
  title: { color: colors.text, fontSize: fontSize.xxl, fontWeight: '700' },
  subtitle: {
    color: colors.textMuted,
    fontSize: fontSize.md,
    marginTop: spacing.sm,
    lineHeight: 22,
  },
  card: { marginTop: spacing.md },
  label: { color: colors.text, fontSize: fontSize.md, fontWeight: '600', marginBottom: spacing.sm },
  hint: {
    color: colors.textMuted,
    fontSize: fontSize.sm,
    marginBottom: spacing.sm,
    lineHeight: 20,
  },
});
